---
- hosts: pfsense
  remote_user: root
  gather_facts: false
  #connection: paramiko
  collections:
    - pfsensible.core

  #remote_user: xo
  #remote_user: user
  #remote_user: ansible
  #remote_user: ebbestad
  #become: yes
  #become_method: sudo
  vars:
    network_card: em1
    vlan: 2
    interface_name: prod


  tasks:
  - name: remove vlan pfsense
    pfsense_vlan:
      interface: "{{ network_card }}"
      vlan_id: "{{ vlan }}"
      descr: "{{ interface_name }}"
      priority: 0
      #state: absent
      state: absent

  - name: remove interface vlan
    pfsense_interface:
      interface: "{{ network_card }}.{{ vlan }}"
      descr: "{{ interface_name }}"
      enable: False
      state: absent

